// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpgg2zxn1vtj_DRnunoilS0UJXeEM5JiI',
    appId: '1:711205798289:web:86284f6400715e1d14da30',
    messagingSenderId: '711205798289',
    projectId: 'tko-app',
    authDomain: 'tko-app.firebaseapp.com',
    storageBucket: 'tko-app.firebasestorage.app',
    measurementId: 'G-3ZE1BZPNL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySVSkk24EVw6RmfQAJPleKuHoXLOvdKQ',
    appId: '1:711205798289:android:c1226d347ab801d114da30',
    messagingSenderId: '711205798289',
    projectId: 'tko-app',
    storageBucket: 'tko-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1C6tHAj2IaiPGpzTXX57Sv2Hvgftaafg',
    appId: '1:711205798289:ios:d7de98682b9f63e014da30',
    messagingSenderId: '711205798289',
    projectId: 'tko-app',
    storageBucket: 'tko-app.firebasestorage.app',
    iosBundleId: 'com.example.tkoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1C6tHAj2IaiPGpzTXX57Sv2Hvgftaafg',
    appId: '1:711205798289:ios:d7de98682b9f63e014da30',
    messagingSenderId: '711205798289',
    projectId: 'tko-app',
    storageBucket: 'tko-app.firebasestorage.app',
    iosBundleId: 'com.example.tkoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpgg2zxn1vtj_DRnunoilS0UJXeEM5JiI',
    appId: '1:711205798289:web:60e42238dd4c6c7114da30',
    messagingSenderId: '711205798289',
    projectId: 'tko-app',
    authDomain: 'tko-app.firebaseapp.com',
    storageBucket: 'tko-app.firebasestorage.app',
    measurementId: 'G-3542EPG81F',
  );
}
